name: Run Integration Tests on Emulator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '35'
          ndk-version: '23.1.7779620'

      # Step 2: Install required system images and platform tools
      - name: Install required system images and platform tools
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-35;google_apis;arm64-v8a"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3"

      # Step 3: Create the AVD (Android Virtual Device)
      - name: Create Android Emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-35;google_apis;arm64-v8a" -d "pixel_5" --force

      # Step 4: Start the Android Emulator
      - name: Start Emulator (disable HVF)
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window -no-accel -gpu swiftshader_indirect &
          sleep 120  # Increase wait time to ensure emulator starts up
          adb wait-for-device
          adb shell input keyevent 82
          # Check if the emulator is running
          emulator -list-avds
          adb devices

      # Step 5: Run Integration Tests
      - name: Run integration tests
        run: |
          flutter test integration_test
