name: Flutter Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration_test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      - name: Disable Flutter analytics
        run: |
          flutter config --no-analytics
          flutter --disable-telemetry

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Create Android emulator
        run: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-35;google_apis;arm64-v8a"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-35;google_apis;arm64-v8a" --device "pixel_5"

      - name: Start emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window &
          sleep 60
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
